# Generated by Django 3.1.5 on 2021-02-20 16:50

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companie', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pozitie', models.CharField(blank=True, max_length=50, null=True)),
                ('locatie', models.CharField(blank=True, max_length=50, null=True)),
                ('descrierea_jobului', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
                ('promovat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pozitie',
                'verbose_name_plural': 'Pozitii',
            },
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
