# Generated by Django 3.1.5 on 2021-02-21 13:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pozitie',
            old_name='pozitie',
            new_name='denumirea_pozitiei',
        ),
        migrations.AlterField(
            model_name='pozitie',
            name='descrierea_jobului',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True),
        ),
    ]
